sonar.projectKey=readify-frontend
sonar.projectName=Readify Frontend
sonar.sources=.
sonar.exclusions=node_modules/**,.next/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.token=sqa_54842c607ef3089d75b42de64051451087fb4320