sonar.projectKey=readify-frontend
sonar.projectName=Readify Frontend
sonar.sources=.
sonar.exclusions=node_modules/**,.next/**
sonar.token=sqa_4e39ba54e7a90ed9d9f5bcddcb1a538ebf528aca
sonar.host.url=http://172.21.0.11:9000